# Plugins
gems:             ['jekyll-paginate', 'jekyll-gist', 'jekyll-github-metadata']

# Dependencies
# highlighter:      rouge
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

# Permalinks
permalink:        pretty

# Setup
title:            Cyrface
tagline:          Bridging Cytoscape with R
description:      "Cyrface establishes an interface between R and Cytoscape"
#url:              https://github.com/saezlab/projectDocumentationTemplate
baseurl:          /cyrface/
toollogo:         /cyrface/cyrface_logo.png

author:
  name:           'Emanuel Goncalves'

paginate:         5

# Custom vars
version:          2.0.0

github:
  repo:           https://github.com/saezlab/cyrface
